title: Kuper-xx Blog
description: "A Blog Talking Some Personal Stuff"
author:
  name: "Kuper-xx"
  email: "juanigkauper.work@gmail.com"
  url: "https://kuper-xx.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Kuper-xx"
year : "2024"
